on:
  push:
  schedule:
    - cron: '30 2 * * 0'
name: build
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.8', '8.10', '9.0', '9.2']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          - ghc: '9.0'
            os: windows-latest
    name: Build Package
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Build library
        run: cabal build
      - name: Run tests
        run: cabal new-test --test-show-details=direct
