on: [push]
name: ci
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.6', '8.8', '8.10', '9.0']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Build Package
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Build library
        run: cabal build
      - name: Run tests
        run: cabal new-test --test-show-details=direct
